name: dcz
recipe: drupal8

config:
  webroot: docroot
  ssl: true
  xdebug: true
  drush: 9
  overrides:
    volumes:
      - ${HOME}/.lando/composer_cache:/var/www/.composer

services:
  database:
    portforward: 3310

  mailhog:
    type: mailhog
    hogfrom:
      - appserver
