# Note that the example .travis.yml file for child projects lives in /install.
sudo: true
language: php
dist: trusty

php:
  - 7.1

matrix:
  fast_finish: true

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - BUILD_DIR=$TRAVIS_BUILD_DIR

jdk:
  - oraclejdk8

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - "vendor"
  # Cache front end dependecies to dramatically improve build time.
  # - "docroot/themes/custom/mytheme/node_modules"
  # - "docroot/themes/custom/mytheme/bower_components"

addons:
  ssh_known_hosts:
  - svn-1745.prod.hosting.acquia.com
  chrome: stable

# @see https://docs.travis-ci.com/user/notifications
notifications:
 - slack:
    rooms:
      - drupalcz:7SUVOYlvaxuqA7PGJ5xu8Afs#dcz-web

before_install:
  # Refs SSH keys on free Travis.
  - openssl aes-256-cbc -K $encrypted_76cf46cb768e_key -iv $encrypted_76cf46cb768e_iv -in .travis/dcz_travis_ssh_key.enc -out $HOME/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 $HOME/deploy_rsa
  - ssh-add $HOME/deploy_rsa
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install
  # Exit build early if only documentation was changed in a Pull Request.
  - source ${BLT_DIR}/scripts/travis/exit_early

install:
  - source ${BLT_DIR}/scripts/travis/setup_environment
  - source ${BLT_DIR}/scripts/travis/setup_project

script:
  - source ${BLT_DIR}/scripts/travis/run_tests

deploy:
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: develop
       php: 7.1
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: master
       php: 7.1
#   - provider: script
#     script: "${BLT_DIR}/scripts/travis/deploy_tag"
#     skip_cleanup: true
#     on:
#       tags: true
#       php: 7.1
