<?php

/**
 * @file
 * Contains dropguard.module.
 */

/**
 * Constants definition.
 */
define('DROPGUARD_DISTRIBUTION_IS_SOLID', 1);

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dropguard_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the dropguard module.
    case 'help.page.dropguard':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides integration with the Drop Guard service to automate Drupal updates.') . '</p>';
      return $output;

    default:
  }

  return FALSE;
}

/**
 * Returns info about site's enabled modules and themes.
 *
 * @param $distribution_update
 *   Contains value which indicates how distribution should be updated
 *   (if it is enabled in the current project).
 *
 * @return array
 *   List of enabled modules, themes, profiles and Drupal core which
 *   should be tracked for possible updates.
 */
function dropguard_enabled_projects_info($distribution_update) {

  $themes = \Drupal::service('theme_handler')->rebuildThemeData();
  $modules = system_rebuild_module_data();

  $projects = $themes + $modules;

  uasort($modules, 'system_sort_modules_by_info_name');

  // Check if web site is running on a custom profile.
  $custom_profile = _dropguard_custom_profile_installed();

  // Drupal doesn't support profile inheritance out of the box. But there are
  // several patches which allow to do it. To cover that rare case we have to
  // support base profile integration as well.
  $custom_base_profile = drupal_get_profile();

  $enabled_projects = array();

  foreach ($projects as $project_name => $project) {

    // We don't care about disabled and core's projects.
    $project_is_enabled = !empty($project->status);
    $core_project = !empty($project->info['project']) && $project->info['project'] == 'drupal';

    // If project doesn't have datestamp from drupal.org bot, then it was not
    // downloaded from drupal.org or was modified. We can track only projects
    // which were downloaded from drupal.org.
    $no_datestamp = empty($project->info['datestamp']);
    if (!$project_is_enabled || $core_project || $no_datestamp) {
      continue;
    }

    // Drop Guard also need a path to project. This is necessary to help
    // Drop Guard to find a proper project location and replace it with a new
    // version.
    $project_path = drupal_get_path($project->info['type'], $project_name);

    // Here is implemented distribution support.
    foreach (array($custom_profile, $custom_base_profile) as $profile) {
      if (!empty($profile)) {

        // If current project is actually a profile, then mark it as a profile
        // for Drop Guard.
        if ($profile == $project_name) {
          $project->info['type'] = 'profile';
        }

        // If distribution should be updated as a solid project then we have to
        // remove all modules and themes which are inside of the current
        // distribution from the list of tracked projects.
        if ($distribution_update == DROPGUARD_DISTRIBUTION_IS_SOLID) {
          $profile_path = drupal_get_path('profile', $profile);
          if (strpos($project_path, $profile_path . '/') === 0) {
            continue(2);
          }
        }
        // If each module and theme inside of distribution should be updated
        // separately then we shouldn't check for distribution update, because
        // it may override updates for modules and themes inside of it.
        elseif ($profile == $project_name) {
          continue(2);
        }
      }
    }

    // If project doesn't have a path, it means that most likely it was removed
    // from the code, but not from the database. To prevent issues with such
    // projects, we also have to exclude them from list of tracked projects.
    // @TODO May not be relevant in D8, as we have no 'disable' per se.
    if (empty($project_path)) {
      continue;
    }

    // We need to have info only about base modules or themes. For example,
    // we don't need to retrieve information about views_ui module, because it
    // is part of views module, and if views_ui will have updates, then these
    // updates will be reflected inside of views project.
    $base_project = !empty($project->info['project']) && $project_name == $project->info['project'];

    // Collect info about base modules.
    if ($base_project) {
      $enabled_projects[$project_name] = array(
        'name' => $project->info['name'],
        'version' => $project->info['version'],
        'type' => $project->info['type'],
        'path' => $project_path,
        'datestamp' => $project->info['datestamp'],
      );
    }

  }

  // Add info about drupal core.
  $enabled_projects['drupal'] = array(
    'name' => 'Drupal',
    'version' => \Drupal::VERSION,
    'type' => 'core',
    'path' => '',
  );

  return $enabled_projects;
}

/**
 * Encrypts data.
 *
 * @param $data
 *   Data which has to be encrypted.
 *
 * @return string
 *   Base64-encoded and encrypted data.
 */
function dropguard_encrypt($data) {

  // Make string from data, if it is not a string yet.
  $data = !is_string($data) ? serialize($data) : $data;

  // Encrypt the data to $encrypted using the public key.
  $public_key = \Drupal::config('dropguard.settings')->get('dropguard.key');

  // Generate random password.
  $password = user_password();

  // We can't encrypt data with public method directly, because
  // openssl_public_encrypt() method doesn't work with big strings. So we have
  // to encrypt data with random password first, then encrypt a random password
  // with public key and send it to the Drop Guard. So no one will decrypt the
  // data unless he got decrypted password, which is encrypted with public key
  // and can be decrypted only with private key.
  $encrypted_data = @openssl_encrypt($data, 'aes128', $password);
  openssl_public_encrypt($password, $encrypted_password, base64_decode($public_key));

  return array(
    'data' => base64_encode($encrypted_data),
    'password' => base64_encode($encrypted_password),
  );
}

/**
 * Checks if current web site uses custom distribution.
 */
function _dropguard_custom_profile_installed() {

  $profile = drupal_get_profile();
  return in_array($profile, array('minimal', 'standard', 'testing')) ? FALSE : $profile;
}
