<?php

/**
 * @file
 * Allows support of a new view handler.
 */

/**
 * Implements hook_theme().
 */
function jssor_theme() {
  return array(
    'views_view_jssor' => array(
      'variables' => array(
        'view' => NULL,
        'rows' => NULL,
      ),
      'file' => 'jssor.theme.inc',
    ),
    'views_view_jssor_row' => array(
      'variables' => array(
        'view' => NULL,
        'rows' => NULL,
      ),
      'file' => 'jssor.theme.inc',
    ),
    'images_jssor_formatter' => array(
      'render element' => 'element',
      'file' => 'jssor.theme.inc',
    ),
    'image_jssor_formatter' => array(
      'variables' => array(
        'item' => NULL,
        'item_attributes' => NULL,
        'url' => NULL,
        'image_style' => NULL,
        'caption' => FALSE
      ),
      'file' => 'jssor.theme.inc',
    ),
  );
}

/**
 * Implements hook_views_pre_render().
 */
function jssor_views_pre_render($view) {
  if ($view->storage->id() === 'jssor') {
  }

  return $view;
}
