version: 1

update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_type: "development"
          update_type: "security"
      - match:
          dependency_type: "production"
          update_type: "security"
