<?php

/**
 * @file
 * Contains dcz_apd.module.
 */

/**
 * Implements hook_entity_extra_field_info().
 */
function dcz_apd_entity_extra_field_info() {
  $extra = [];

  $extra['apd_membership']['apd_membership']['display']['computed_status'] = [
    'label' => t('Human-readable status'),
    'description' => 'Display human-readable status.',
    'weight' => 0,
    'visible' => FALSE,
  ];
  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function dcz_apd_apd_membership_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  /** @var \Drupal\dcz_apd\Entity\ApdMembershipInterface $entity */
  if ($display->getComponent('computed_status')) {
    $build['computed_status'] = [
      '#type' => 'markup',
      '#markup' => '<strong>Stav přihlášky</strong>' . $entity->getHumanStatus(),
    ];
  }
}
